<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" total="2" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="45002" started-at="2021-10-20T07:19:53Z" finished-at="2021-10-20T07:20:38Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="45002" started-at="2021-10-20T07:19:53Z" finished-at="2021-10-20T07:20:38Z">
      <class name="com.Repairshop.tests.LoginTest">
        <test-method status="PASS" signature="SetUp()[pri:0, instance:com.Repairshop.tests.LoginTest@18ce0030]" name="SetUp" is-config="true" duration-ms="1566" started-at="2021-10-20T12:49:53Z" finished-at="2021-10-20T12:49:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SetUp -->
        <test-method status="PASS" signature="SetUp()[pri:0, instance:com.Repairshop.tests.LoginTest@18ce0030]" name="SetUp" is-config="true" duration-ms="1612" started-at="2021-10-20T12:49:53Z" finished-at="2021-10-20T12:49:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SetUp -->
        <test-method status="PASS" signature="initialie()[pri:0, instance:com.Repairshop.tests.LoginTest@18ce0030]" name="initialie" is-config="true" duration-ms="2" started-at="2021-10-20T12:49:54Z" finished-at="2021-10-20T12:49:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialie -->
        <test-method status="FAIL" signature="CreateCustomer2()[pri:0, instance:com.Repairshop.tests.LoginTest@18ce0030]" name="CreateCustomer2" duration-ms="25876" started-at="2021-10-20T12:49:54Z" finished-at="2021-10-20T12:50:20Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.Repairshop.tests.LoginTest.CreateCustomer2(LoginTest.java:95)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CreateCustomer2 -->
        <test-method status="FAIL" signature="CreateCustomer()[pri:0, instance:com.Repairshop.tests.LoginTest@18ce0030]" name="CreateCustomer" duration-ms="38411" started-at="2021-10-20T12:49:54Z" finished-at="2021-10-20T12:50:33Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.Repairshop.tests.LoginTest.CreateCustomer(LoginTest.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CreateCustomer -->
        <test-method status="PASS" signature="initialie()[pri:0, instance:com.Repairshop.tests.LoginTest@18ce0030]" name="initialie" is-config="true" duration-ms="0" started-at="2021-10-20T12:49:54Z" finished-at="2021-10-20T12:49:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialie -->
        <test-method status="PASS" signature="TearDown(org.testng.ITestResult)[pri:0, instance:com.Repairshop.tests.LoginTest@18ce0030]" name="TearDown" is-config="true" duration-ms="667" started-at="2021-10-20T12:50:20Z" finished-at="2021-10-20T12:50:21Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=CreateCustomer2 status=FAILURE method=LoginTest.CreateCustomer2()[pri:0, instance:com.Repairshop.tests.LoginTest@18ce0030] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
        <test-method status="PASS" signature="TearDown(org.testng.ITestResult)[pri:0, instance:com.Repairshop.tests.LoginTest@18ce0030]" name="TearDown" is-config="true" duration-ms="4759" started-at="2021-10-20T12:50:33Z" finished-at="2021-10-20T12:50:38Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=CreateCustomer status=FAILURE method=LoginTest.CreateCustomer()[pri:0, instance:com.Repairshop.tests.LoginTest@18ce0030] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
      </class> <!-- com.Repairshop.tests.LoginTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
