<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="36909" started-at="2021-10-18T09:21:50Z" finished-at="2021-10-18T09:22:27Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="36909" started-at="2021-10-18T09:21:50Z" finished-at="2021-10-18T09:22:27Z">
      <class name="com.Repairshop.tests.LoginTest">
        <test-method status="PASS" signature="SetUp()[pri:0, instance:com.Repairshop.tests.LoginTest@4da4253]" name="SetUp" is-config="true" duration-ms="1470" started-at="2021-10-18T14:51:50Z" finished-at="2021-10-18T14:51:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SetUp -->
        <test-method status="PASS" signature="SetUp()[pri:0, instance:com.Repairshop.tests.LoginTest@4da4253]" name="SetUp" is-config="true" duration-ms="1470" started-at="2021-10-18T14:51:50Z" finished-at="2021-10-18T14:51:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SetUp -->
        <test-method status="FAIL" signature="CreateCustomer2()[pri:0, instance:com.Repairshop.tests.LoginTest@4da4253]" name="CreateCustomer2" duration-ms="30219" started-at="2021-10-18T14:51:51Z" finished-at="2021-10-18T14:52:22Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.Repairshop.tests.LoginTest.CreateCustomer2(LoginTest.java:88)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CreateCustomer2 -->
        <test-method status="PASS" signature="initialie()[pri:0, instance:com.Repairshop.tests.LoginTest@4da4253]" name="initialie" is-config="true" duration-ms="0" started-at="2021-10-18T14:51:51Z" finished-at="2021-10-18T14:51:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialie -->
        <test-method status="PASS" signature="initialie()[pri:0, instance:com.Repairshop.tests.LoginTest@4da4253]" name="initialie" is-config="true" duration-ms="0" started-at="2021-10-18T14:51:51Z" finished-at="2021-10-18T14:51:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialie -->
        <test-method status="PASS" signature="CreateCustomer()[pri:0, instance:com.Repairshop.tests.LoginTest@4da4253]" name="CreateCustomer" duration-ms="23506" started-at="2021-10-18T14:51:51Z" finished-at="2021-10-18T14:52:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CreateCustomer -->
        <test-method status="PASS" signature="TearDown(org.testng.ITestResult)[pri:0, instance:com.Repairshop.tests.LoginTest@4da4253]" name="TearDown" is-config="true" duration-ms="4710" started-at="2021-10-18T14:52:15Z" finished-at="2021-10-18T14:52:20Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=CreateCustomer status=SUCCESS method=LoginTest.CreateCustomer()[pri:0, instance:com.Repairshop.tests.LoginTest@4da4253] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
        <test-method status="PASS" signature="TearDown(org.testng.ITestResult)[pri:0, instance:com.Repairshop.tests.LoginTest@4da4253]" name="TearDown" is-config="true" duration-ms="4726" started-at="2021-10-18T14:52:22Z" finished-at="2021-10-18T14:52:27Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=CreateCustomer2 status=FAILURE method=LoginTest.CreateCustomer2()[pri:0, instance:com.Repairshop.tests.LoginTest@4da4253] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
      </class> <!-- com.Repairshop.tests.LoginTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
